apiVersion: apps/v1
kind: Deployment
metadata:
    name: traefik
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: traefik
    template:
        metadata:
            labels:
                app: traefik
        spec:
            containers:
              - name: traefik
                image: {{ .Values.image.repository }}: {{ .Values.image.tag }}
                ports:
                 - containerPort: 80
